version: 0.1
phases:
  pre_build:
    commands:
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"saitejamalladi\" --password=\"Dream#1234\""
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "mvn clean package -DskipTests=true"
      - "docker --version"
      - "docker build -f Dockerfile.custom -t demo ."
      - "docker tag demo saitejamalladi/demo"
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push saitejamalladi/demo"
      - echo "Docker image pushed successfully"
      - envsubst < "Dockerrun.aws.json.template" > "Dockerrun.aws.json"
      - echo "Dockerrun.aws.json.template transported successfully"
artifacts:
  files:
    - 'Dockerrun.aws.json'
    - '.ebextensions/**/*'