---
version: 0.1
phases:
  pre_build:
    commands:
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"saitejamalladi\" --password=\"Dream#1234\""
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t saitejamalladi/demo_demo ."
      - "docker tag saitejamalladi/demo_demo saitejamalladi/demo_demo:latest"
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push saitejamalladi/demo_demo:latest"