version: 0.1
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"saitejamalladi\" --password=\"Dream#1234\""
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t demo ."
      - "docker tag demo saitejamalladi/demo"
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push saitejamalladi/demo"