version: 0.2
env:
  variables:
    ECS_QA: "teja-demo-test"
    IMAGEDEFINITIONS_QA: "imagedefinitions.json"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=039452625179.dkr.ecr.ap-south-1.amazonaws.com/test-repo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -DskipTests
      - mvn package -DskipTests
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":'\"$ECS_QA\"',"imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > $IMAGEDEFINITIONS_QA
artifacts:
  files:
    - target/mmm-orchestrator.jar
    - $IMAGEDEFINITIONS_QA