version: '3'
services:
  demo:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MY_PARAM1=para1
      - MY_PARAM2=para2